apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: default
spec:
  override:
    nodeagent:
      extraConfd:
        configDataMap:
              postgres.yaml: |-
                cluster_check: true
                init_config:
                instances:
                  - dbm: true
                    host: vitor-m.postgres.database.azure.com
                    port: 5432
                    username: 'datadog'
                    password: ''
                    ssl: 'require'
                    azure:
                      deployment_type: 'FlexibleServer'
                      fully_qualified_domain_name: 'vitor-m.postgres.database.azure.com'  
  global:
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    site: "datadoghq.com"
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
      instrumentation:
        enabled: true
        libVersions:
          js: "5"
    admissionController:
      enabled: true  # ✅ Enables APM Auto-Injection
    logCollection:
      enabled: true
      containerCollectAll: false
    usm:
      enabled: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true  
