apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default  # Ensures this runs in the default namespace
  labels:
    tags.datadoghq.com/env: 'prod'
    tags.datadoghq.com/service: 'node-app-kuber'
  annotations:
    ad.datadoghq.com/service.check_names: '["postgres"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |
      [
        {
          "dbm": true,
          "host": "vitor-m.postgres.database.azure.com",
          "port": 5432,
          "username": "datadog",
          "password": "",
          "ssl": "require",
          "azure": {
            "deployment_type": "flexible_server",
            "fully_qualified_domain_name": "vitor-m.postgres.database.azure.com"
          }
        }
      ]
spec:
  selector:
    app: postgres  # Ensure this matches your PostgreSQL pod labels
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: postgres
